# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    imager_params:
        root_path: '%kernel.root_dir%'
        web_path: ~

        filter_sets:
            news_thumb: {filter: thumbnail, width: 500, height: 500, crop_mode: true, allow_upscale: true, quality: 80 }

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.serializer:
        class: AppBundle\Service\Serializer

    app.tokens.cors_listener:
        class: AppBundle\EventListener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@security.password_encoder","@router"]

    vich_uploader.custom_directory_namer:
        class: AppBundle\Service\DirectoryNamer
        arguments: ["@request_stack", %app.path.upload_images%]

    Imager:
        class:  AppBundle\Service\Imager
        arguments: ["@request_stack", %imager_params%]

    open_embed:
        class:  AppBundle\Service\Embed
