framework:
    translator: { fallbacks: [ "en" ] }

parameters:
    app.path.upload_images: /images/uploads

vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: %app.path.upload_images%
            upload_destination: '%kernel.root_dir%/../web%app.path.upload_images%'
            namer: vich_uploader.namer_uniqid
            directory_namer: vich_uploader.custom_directory_namer

easy_admin:
    site_name: 'Blinky Bill Music'

    design:
        brand_color: '#1ABC9C'
        form_theme: 'vertical'

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

imports:
    - { resource: article.yml }
    - { resource: role.yml }
    - { resource: user.yml }
    - { resource: video.yml }
    - { resource: rbma.yml }
    - { resource: press.yml }
