easy_admin:
    entities:
        Link:
            class: AppBundle\Entity\Press
            label: 'Press Links'
            list:
                title: 'Press Links'
                fields:
                    - id
                    - title
                    - url
                    - published
                    - { property: 'updatedAt', format: 'j/n/Y' }
                    - { property: 'createdAt', format: 'j/n/Y' }

            form:
                title: 'Press Links'
                fields:
                    - { type: 'section', label: 'Link Details' }
                    - title
                    - url
                    - published
                    - { type: 'divider' }
